#pragma once

// AUTO-GENERATED by model/tools/generate_robot_model.py from model/tilt.urdf.
// Do not edit by hand: change the URDF and regenerate.
//
// Base frame B: torso axes (+x forward, +y left, +z up), origin at the midpoint
// of the two hip points H (intersection of each leg's hip-roll and hip-pitch
// axes). Lengths in mm, mass in kg, angles in rad. Leg index 0 = LEFT, 1 = RIGHT.
// A joint transform is: child = parent * Translate(origin) * rotation * Rot(axis, q).

namespace tilt::model {

struct JointSpec {
    float origin_mm[3];
    float rotation[3][3];
    float axis[3];
};

struct LinkInertial {
    float mass_kg;
    float com_mm[3];  // In the link frame.
};

// Origin of B expressed in the URDF torso frame.
inline constexpr float BASE_IN_TORSO_MM[3] = {-35.0142f, 70.9123f, 144.053895f};

// [leg][hip_roll, hip_pitch, knee_pitch]; hip_roll's parent is B.
inline constexpr JointSpec LEG_JOINT[2][3] = {
    {{{18.2f, 13.0f, 0.000104813102f}, {{-3.6732051e-06f, -3.6732051e-06f, -1.0f}, {-1.0f, 1.34924357e-11f, 3.6732051e-06f}, {0.0f, 1.0f, -3.6732051e-06f}}, {0.0f, 0.0f, -1.0f}}, {{-24.0f, 0.0f, 18.2f}, {{-3.6732051e-06f, -3.6732051e-06f, 1.0f}, {-1.0f, 1.34924357e-11f, -3.6732051e-06f}, {0.0f, -1.0f, -3.6732051e-06f}}, {0.0f, 0.0f, -1.0f}}, {{67.9996f, 0.1f, 0.0f}, {{1.0f, 0.0f, 0.0f}, {0.0f, 1.0f, 0.0f}, {0.0f, 0.0f, 1.0f}}, {0.0f, 0.0f, -1.0f}}},
    {{{18.2f, -13.0f, 0.000104813102f}, {{-3.6732051e-06f, 3.6732051e-06f, -1.0f}, {1.0f, 1.34924357e-11f, -3.6732051e-06f}, {0.0f, -1.0f, -3.6732051e-06f}}, {0.0f, 0.0f, -1.0f}}, {{-24.0f, 0.0f, 18.2f}, {{-3.6732051e-06f, 2.65358979e-06f, 1.0f}, {0.0f, -1.0f, 2.65358979e-06f}, {1.0f, 9.74717957e-12f, 3.6732051e-06f}}, {0.0f, 0.0f, 1.0f}}, {{0.1f, -67.9996f, 0.0f}, {{-3.6732051e-06f, 1.0f, 0.0f}, {-1.0f, -3.6732051e-06f, 0.0f}, {0.0f, 0.0f, 1.0f}}, {0.0f, 0.0f, 1.0f}}},
};

// Fixed calf -> sole frame (sole frame: z up and x forward when the foot is flat).
inline constexpr JointSpec SOLE_FIXED[2] = {
    {{76.4293f, 2.69369f, -18.3993f}, {{-0.342027494f, 3.88156484e-06f, -0.939689945f}, {0.939689945f, 7.52502425e-08f, -0.342027494f}, {-1.25689e-06f, -1.0f, -3.6732051e-06f}}, {0.0f, 0.0f, 1.0f}},
    {{76.4267f, -2.69444f, -18.1989f}, {{-0.342027494f, -6.55523823e-06f, -0.939689945f}, {-0.939689945f, -7.27042822e-06f, 0.342027494f}, {-9.07402e-06f, 1.0f, -3.6732051e-06f}}, {0.0f, 0.0f, 1.0f}},
};

// [leg][hip, thigh, calf] inertials in their link frames.
inline constexpr LinkInertial LEG_LINK[2][3] = {
    {{0.0102f, {-11.9393f, 8.041e-06f, 22.9228f}}, {0.07791f, {21.1469f, 0.0430366f, -18.4847f}}, {0.09434f, {30.5877f, 0.0315603f, -18.5256f}}},
    {{0.0102f, {-11.9393f, 8.041e-06f, 22.9228f}}, {0.07791f, {0.0430367f, -21.1469f, -18.4847f}}, {0.09434f, {30.5877f, -0.0315613f, -18.4448f}}},
};

// Torso inertial in B.
inline constexpr LinkInertial TORSO = {0.51291f, {-0.0991000004f, -0.1601f, 84.4541048f}};

// Head (parent B) and arms [leg-side][pitch (parent B), roll (parent shoulder)].
inline constexpr JointSpec HEAD_PITCH = {{-0.1f, 23.4f, 208.919105f}, {{-3.6732051e-06f, 1.0f, 3.6732051e-06f}, {0.0f, -3.6732051e-06f, 1.0f}, {1.0f, 3.6732051e-06f, 1.34924357e-11f}}, {0.0f, 0.0f, 1.0f}};
inline constexpr LinkInertial HEAD = {0.29357f, {5.06142f, 38.219f, -24.1988f}};
inline constexpr JointSpec ARM_JOINT[2][2] = {
    {{{-0.1f, 112.2997f, 102.019105f}, {{1.0f, 0.0f, 0.0f}, {0.0f, -3.6732051e-06f, -1.0f}, {0.0f, 1.0f, -3.6732051e-06f}}, {0.0f, 0.0f, -1.0f}}, {{18.35f, 1.47e-07f, -23.0f}, {{-3.6732051e-06f, 0.0f, 1.0f}, {0.0f, 1.0f, 0.0f}, {-1.0f, 0.0f, -3.6732051e-06f}}, {0.0f, 0.0f, 1.0f}}},
    {{{-0.1f, -112.5f, 102.019105f}, {{1.0f, 0.0f, 0.0f}, {0.0f, -3.6732051e-06f, 1.0f}, {0.0f, -1.0f, -3.6732051e-06f}}, {0.0f, 0.0f, 1.0f}}, {{18.35f, 1.47e-07f, -23.0f}, {{-3.6732051e-06f, 0.0f, 1.0f}, {0.0f, 1.0f, 0.0f}, {-1.0f, 0.0f, -3.6732051e-06f}}, {0.0f, 0.0f, 1.0f}}},
};
inline constexpr LinkInertial ARM_LINK[2][2] = {
    {{0.01015f, {-0.808697f, -6e-09f, -11.5843f}}, {0.02385f, {17.8203f, -1.82182f, -17.9663f}}},
    {{0.01015f, {-0.808697f, -6e-09f, -11.5843f}}, {0.02385f, {17.8203f, 1.82182f, -17.9663f}}},
};

inline constexpr float TOTAL_MASS_KG = 1.23938f;

// ---- Analytic IK parameters (derived from the same chain) ----
// Hip point H of each leg in B.
inline constexpr float HIP_POINT_MM[2][3] = {
    {8.8156945e-05f, 13.0000669f, -6.11736803e-06f},
    {-8.8156945e-05f, -13.0000669f, 6.11736806e-06f},
};
// Sole lateral offset from H in the roll frame (+ = left). Constant because the
// pitch and knee axes are parallel to the roll frame's y axis.
inline constexpr float SOLE_LATERAL_MM[2] = {42.3998305f, -42.1992642f};
// Sagittal (x, z) vectors at q = 0: H -> knee, and knee -> sole.
inline constexpr float THIGH_XZ_MM[2][2] = {{0.100249777f, -67.9995556f}, {-0.0995739085f, -67.9995685f}};
inline constexpr float SHANK_XZ_MM[2][2] = {{2.69397074f, -76.4292225f}, {2.69513516f, -76.4266319f}};
// Sole pitch (about +y) when hip_pitch + knee_pitch = 0.
inline constexpr float SOLE_PITCH_AT_ZERO_RAD = -0.349077346f;

}  // namespace tilt::model
