// Host tests for the mk.2 leg kinematics (tilt_kinematics).
// kinematics_reference.h holds MuJoCo ground truth generated by
// model/tools/generate_robot_model.py --reference.

#include <cmath>
#include <cstdio>
#include <initializer_list>

#include "kinematics_reference.h"
#include "tilt/kinematics/RobotModel.h"
#include "tilt_kinematics.h"

namespace {

constexpr float kFkToleranceMm = 0.05f;
constexpr float kRotationTolerance = 1.0e-4f;
constexpr float kRoundTripRad = 1.0e-3f;
constexpr float kRoundTripMm = 0.01f;
int s_failures = 0;

void expectTrue(bool condition, const char* expression, const char* test_name) {
    if (!condition) {
        std::printf("FAIL [%s] %s\n", test_name, expression);
        ++s_failures;
    }
}

void expectNear(float actual, float expected, float tolerance,
                const char* expression, const char* test_name) {
    if (!(std::fabs(actual - expected) <= tolerance)) {
        std::printf("FAIL [%s] %s: expected %.6f, got %.6f (tol %.6f)\n",
                    test_name, expression, expected, actual, tolerance);
        ++s_failures;
    }
}

#define EXPECT_TRUE(test_name, expression) \
    expectTrue((expression), #expression, test_name)
#define EXPECT_NEAR(test_name, actual, expected, tolerance) \
    expectNear((actual), (expected), (tolerance), #actual, test_name)

constexpr float rad(float degrees) { return degrees * tilt::DEG2RAD; }

float distance(const tilt::Vec3& a, const tilt::Vec3& b) {
    const float dx = a.x - b.x;
    const float dy = a.y - b.y;
    const float dz = a.z - b.z;
    return std::sqrt(dx * dx + dy * dy + dz * dz);
}

void testForwardKinematicsAgainstMujoco() {
    constexpr char kTest[] = "T1 FK vs MuJoCo";
    float worst_mm = 0.0f;
    float worst_rot = 0.0f;
    for (const auto& sample : kinematics_reference::SAMPLES) {
        for (const tilt::Leg leg : {tilt::Leg::LEFT, tilt::Leg::RIGHT}) {
            const bool left = leg == tilt::Leg::LEFT;
            const float* theta = left ? sample.left_theta : sample.right_theta;
            const float* sole = left ? sample.left_sole_mm : sample.right_sole_mm;
            const auto& rotation = left ? sample.left_sole_R : sample.right_sole_R;
            const tilt::LegFrames frames = tilt::fk_leg(leg, theta);
            const float error = distance(frames.sole.p, {sole[0], sole[1], sole[2]});
            if (error > worst_mm) worst_mm = error;
            for (int r = 0; r < 3; ++r) {
                for (int c = 0; c < 3; ++c) {
                    const float e = std::fabs(frames.sole.R.m[r][c] - rotation[r][c]);
                    if (e > worst_rot) worst_rot = e;
                }
            }
        }
    }
    std::printf("[%s] %zu samples, worst position %.4f mm, worst rotation %.2e\n",
                kTest, sizeof(kinematics_reference::SAMPLES) /
                           sizeof(kinematics_reference::SAMPLES[0]),
                worst_mm, worst_rot);
    EXPECT_TRUE(kTest, worst_mm <= kFkToleranceMm);
    EXPECT_TRUE(kTest, worst_rot <= kRotationTolerance);
}

void testStandPose() {
    constexpr char kTest[] = "T2 stand pose";
    const float theta[] = {0.0f, rad(-20.0f), rad(+40.0f)};
    for (const tilt::Leg leg : {tilt::Leg::LEFT, tilt::Leg::RIGHT}) {
        const tilt::LegFrames frames = tilt::fk_leg(leg, theta);
        const int i = static_cast<int>(leg);
        const float height = tilt::model::HIP_POINT_MM[i][2] - frames.sole.p.z;
        std::printf("[%s] %s hip-pitch axis -> sole %.3f mm (config %.3f), "
                    "sole x %.3f mm, y %.3f mm\n",
                    kTest, i == 0 ? "LEFT " : "RIGHT", height,
                    tilt::ZERO_POSE_HEIGHT_MM, frames.sole.p.x, frames.sole.p.y);
        EXPECT_NEAR(kTest, height, tilt::ZERO_POSE_HEIGHT_MM, 0.5f);
        EXPECT_NEAR(kTest, frames.sole.p.x, 0.0f, 1.0f);
        // Flat sole: sole frame aligned with B.
        EXPECT_NEAR(kTest, frames.sole.R.m[2][2], 1.0f, 1.0e-4f);
        EXPECT_NEAR(kTest, frames.sole.R.m[0][0], 1.0f, 1.0e-4f);
        EXPECT_NEAR(kTest, tilt::sole_pitch_rad(theta), 0.0f, 1.0e-4f);
    }
}

void testRoundTrip() {
    constexpr char kTest[] = "T3 FK/IK round trip";
    int count = 0;
    float worst_rad = 0.0f;
    float worst_mm = 0.0f;
    for (const tilt::Leg leg : {tilt::Leg::LEFT, tilt::Leg::RIGHT}) {
        for (int roll = -13; roll <= 17; roll += 5) {
            for (int hip = -70; hip <= 15; hip += 5) {
                for (int knee = 5; knee <= 75; knee += 5) {
                    const float theta[] = {rad(static_cast<float>(roll)),
                                           rad(static_cast<float>(hip)),
                                           rad(static_cast<float>(knee))};
                    const tilt::Vec3 sole = tilt::fk_foot(leg, theta);
                    const tilt::IkResult ik = tilt::ik_foot(leg, sole);
                    EXPECT_TRUE(kTest, ik.reachable);
                    for (int j = 0; j < 3; ++j) {
                        const float e = std::fabs(ik.theta[j] - theta[j]);
                        if (e > worst_rad) worst_rad = e;
                    }
                    const float e = distance(tilt::fk_foot(leg, ik.theta), sole);
                    if (e > worst_mm) worst_mm = e;
                    ++count;
                }
            }
        }
    }
    std::printf("[%s] %d poses, worst angle %.2e rad, worst position %.4f mm\n",
                kTest, count, worst_rad, worst_mm);
    EXPECT_TRUE(kTest, worst_rad <= kRoundTripRad);
    EXPECT_TRUE(kTest, worst_mm <= kRoundTripMm);
}

void testWorkspaceBoundary() {
    constexpr char kTest[] = "T4 workspace boundary";
    const tilt::Leg leg = tilt::Leg::LEFT;
    const float* h = tilt::model::HIP_POINT_MM[0];
    const tilt::IkResult too_far = tilt::ik_foot(leg, {h[0], h[1] + 42.4f, h[2] - 250.0f});
    const tilt::IkResult at_hip = tilt::ik_foot(leg, {h[0], h[1], h[2]});
    const tilt::IkResult inside = tilt::ik_foot(leg, {h[0], h[1] + 42.4f, h[2] - 120.0f});
    EXPECT_TRUE(kTest, !too_far.reachable);
    EXPECT_TRUE(kTest, !at_hip.reachable);
    EXPECT_TRUE(kTest, inside.reachable);
    for (const tilt::IkResult* r : {&too_far, &at_hip, &inside}) {
        for (int j = 0; j < 3; ++j) EXPECT_TRUE(kTest, std::isfinite(r->theta[j]));
    }
    const tilt::IkResult nan_target = tilt::ik_foot(leg, {NAN, 0.0f, -100.0f});
    EXPECT_TRUE(kTest, !nan_target.reachable);
}

void testSignConventions() {
    constexpr char kTest[] = "T5 sign conventions";
    const float stand[] = {0.0f, rad(-20.0f), rad(+40.0f)};
    for (const tilt::Leg leg : {tilt::Leg::LEFT, tilt::Leg::RIGHT}) {
        const tilt::Vec3 base = tilt::fk_foot(leg, stand);
        const float roll[] = {rad(5.0f), stand[1], stand[2]};
        const float pitch[] = {0.0f, stand[1] + rad(5.0f), stand[2]};
        const float knee[] = {0.0f, stand[1], stand[2] + rad(5.0f)};
        EXPECT_TRUE(kTest, tilt::fk_foot(leg, roll).y > base.y);    // + roll: foot left
        EXPECT_TRUE(kTest, tilt::fk_foot(leg, pitch).x < base.x);   // + pitch: leg back
        EXPECT_TRUE(kTest, tilt::fk_foot(leg, knee).z > base.z);    // + knee: foot up
    }
}

void testLeftRightSymmetry() {
    constexpr char kTest[] = "T6 left/right symmetry";
    float worst = 0.0f;
    for (int roll = -10; roll <= 10; roll += 5) {
        for (int hip = -50; hip <= 10; hip += 15) {
            for (int knee = 10; knee <= 70; knee += 15) {
                const float left[] = {rad(static_cast<float>(roll)),
                                      rad(static_cast<float>(hip)),
                                      rad(static_cast<float>(knee))};
                const float right[] = {-left[0], left[1], left[2]};
                const tilt::Vec3 l = tilt::fk_foot(tilt::Leg::LEFT, left);
                const tilt::Vec3 r = tilt::fk_foot(tilt::Leg::RIGHT, right);
                const tilt::Vec3 mirrored{r.x, -r.y, r.z};
                const float e = distance(l, mirrored);
                if (e > worst) worst = e;
            }
        }
    }
    // The CAD is not perfectly symmetric (sole lateral offset 42.40 vs 42.20 mm).
    std::printf("[%s] worst mirror mismatch %.3f mm\n", kTest, worst);
    EXPECT_TRUE(kTest, worst <= 0.5f);
}

void testClampToLimits() {
    constexpr char kTest[] = "T7 clamp_to_limits";
    float inside[] = {0.0f, rad(-20.0f), rad(40.0f)};
    EXPECT_TRUE(kTest, tilt::clamp_to_limits(tilt::Leg::LEFT, inside));
    float outside[] = {rad(40.0f), rad(-120.0f), NAN};
    EXPECT_TRUE(kTest, !tilt::clamp_to_limits(tilt::Leg::RIGHT, outside));
    EXPECT_NEAR(kTest, outside[0], tilt::JOINT_LIMIT[1][0].maximum_rad, 1e-6f);
    EXPECT_NEAR(kTest, outside[1], tilt::JOINT_LIMIT[1][1].minimum_rad, 1e-6f);
    EXPECT_TRUE(kTest, std::isfinite(outside[2]));
}

}  // namespace

int main() {
    testForwardKinematicsAgainstMujoco();
    testStandPose();
    testRoundTrip();
    testWorkspaceBoundary();
    testSignConventions();
    testLeftRightSymmetry();
    testClampToLimits();

    if (s_failures == 0) {
        std::printf("All kinematics tests passed.\n");
        return 0;
    }
    std::printf("%d kinematics test assertion(s) failed.\n", s_failures);
    return 1;
}
